networks:
  supplementapp:

services:
  db:
    image: mongo:5
    ports:
      - "27017:27017"
    networks:
      - supplementapp
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - supplementapp
    environment:
      - MONGODB_URI=mongodb://db:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.3
      - MONGODB_DB=supplementapp