networks:
  supplementapp:

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supplementapp
    ports:
      - "5432:5432"
    volumes:
      - .data/db-data:/var/lib/postgresql/data
    networks:
      - supplementapp
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - supplementapp
    environment:
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/supplementapp"