# Heavily influenced by https://olegk.dev/github-actions-and-go, thanks!

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '0 10 * * 1'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['stable', 'oldstable']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Format
      run: gofmt -w -s . && git diff --exit-code

    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Build
      run: go build -o /dev/null ./...

    - name: Test
      run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      continue-on-error: true
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        fail_ci_if_error: false